# Generated by Django 3.2 on 2021-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210523_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
